// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi1kxjDj8r4_7JQX15i1hlbUKBp1wm42w',
    appId: '1:740104548683:web:383a9c8b1c78dc994d78ce',
    messagingSenderId: '740104548683',
    projectId: 'checkit-3bec4',
    authDomain: 'checkit-3bec4.firebaseapp.com',
    storageBucket: 'checkit-3bec4.appspot.com',
    measurementId: 'G-XHF7ZVPVKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeGTA8s25mQeDEpbuc1xlC3hlWVmlO3QU',
    appId: '1:740104548683:android:06b84179e0759ac84d78ce',
    messagingSenderId: '740104548683',
    projectId: 'checkit-3bec4',
    storageBucket: 'checkit-3bec4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAptaYE17bXun9L5C0gNpBp98qTN1-xQOM',
    appId: '1:740104548683:ios:b8404f94dee093064d78ce',
    messagingSenderId: '740104548683',
    projectId: 'checkit-3bec4',
    storageBucket: 'checkit-3bec4.appspot.com',
    iosBundleId: 'com.example.checkIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAptaYE17bXun9L5C0gNpBp98qTN1-xQOM',
    appId: '1:740104548683:ios:b8404f94dee093064d78ce',
    messagingSenderId: '740104548683',
    projectId: 'checkit-3bec4',
    storageBucket: 'checkit-3bec4.appspot.com',
    iosBundleId: 'com.example.checkIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi1kxjDj8r4_7JQX15i1hlbUKBp1wm42w',
    appId: '1:740104548683:web:26c06cf4952e17094d78ce',
    messagingSenderId: '740104548683',
    projectId: 'checkit-3bec4',
    authDomain: 'checkit-3bec4.firebaseapp.com',
    storageBucket: 'checkit-3bec4.appspot.com',
    measurementId: 'G-BMPPJ04PJM',
  );

}